name: 'Prerequisites for tests'
description: 'Consolidated prerequisite steps for tests'
runs:
  using: 'composite'
  steps:
      - name: Setup Node.js environment
        uses: ./.github/actions/setup-node

      - name: Install
        shell: bash
        run: npm install